apiVersion: v1
kind: Service
metadata:
  name: example1
  labels:
    app: example1
spec:
  type: LoadBalancer
  selector:
    app: example1
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080